DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS upgrades CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS routes CASCADE;
DROP TABLE IF EXISTS governors CASCADE;
DROP TABLE IF EXISTS astropaths CASCADE;
DROP TABLE IF EXISTS navigators CASCADE;
DROP TABLE IF EXISTS planets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rogue_traders CASCADE;

DROP FUNCTION IF EXISTS update_rebellion_status CASCADE;
DROP FUNCTION IF EXISTS check_project_resources CASCADE;
DROP FUNCTION IF EXISTS check_upgrade_compatibility CASCADE;
DROP FUNCTION IF EXISTS send_message CASCADE;
DROP FUNCTION IF EXISTS resolve_crisis CASCADE;
DROP FUNCTION IF EXISTS get_empire_resources CASCADE;